### ISSUE TITLE
Normal icons (folder.svg) are not changed

### ISSUE THREAD

**Issue by RaitaroH** [RaitaroH/BreezeDarkIconColors#1]
![screenshot_20180215_140439](https://user-images.githubusercontent.com/19552720/36255912-7a024ce6-1259-11e8-9a0b-d36fb41cc32b.png)

**Comment by Mel34** [comment]
Probably cached. Check your ~/.cache folder for KDE caches, try purging them.

**Comment by RaitaroH** [comment]
@Mel34 I deleted the cache folder, set the icons again, restart plasma just in case and even moved icon cache from /usr/share/icons/breeze-dark.

It doesn't seem to take effect.

**Comment by RaitaroH** [comment]
Found the issue. A file called inode-directory.svg is missing.

**Comment by RaitaroH** [comment]
The inode-directory file was in /mimetypes/64/ so this is why it was defaulting to that. Problem solved, everything is perfect now. Please enjoy.

**Comment by RaitaroH** [comment]
@Mel34 The inode-directory file was in /mimetypes/64/ so this is why it was defaulting to that. Problem solved, everything is perfect now. Please enjoy.
